-- Combined schema setup for a fresh Supabase project.
-- Generated by concatenating supabase/migrations/*.sql in chronological
-- order (skipping 20260706120010_daily_duas.sql, an exact duplicate of
-- 20260708023607's table + seed data).
-- Run this ONCE in the new project's SQL Editor. Wrapped in a
-- transaction so it either fully applies or fully rolls back.

BEGIN;

-- ============================================================
-- FROM: 20260626052323_bf6a7955-93b9-4068-b757-fa4fcb2b4d81.sql
-- ============================================================

-- Profiles
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own profile select" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "own profile insert" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "own profile update" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Habit type enum
CREATE TYPE public.habit_type AS ENUM ('boolean', 'counter', 'checklist');

-- Habits
CREATE TABLE public.habits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  name_ar TEXT,
  type public.habit_type NOT NULL DEFAULT 'boolean',
  unit TEXT,
  target INTEGER,
  sort_order INTEGER NOT NULL DEFAULT 0,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX habits_user_idx ON public.habits(user_id, sort_order);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habits TO authenticated;
GRANT ALL ON public.habits TO service_role;
ALTER TABLE public.habits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own habits all" ON public.habits FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Checklist items
CREATE TABLE public.habit_checklist_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  habit_id UUID NOT NULL REFERENCES public.habits(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX habit_checklist_items_habit_idx ON public.habit_checklist_items(habit_id, sort_order);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habit_checklist_items TO authenticated;
GRANT ALL ON public.habit_checklist_items TO service_role;
ALTER TABLE public.habit_checklist_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own checklist items all" ON public.habit_checklist_items FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.habits h WHERE h.id = habit_id AND h.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.habits h WHERE h.id = habit_id AND h.user_id = auth.uid()));

-- Habit logs (one per habit per day)
CREATE TABLE public.habit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  habit_id UUID NOT NULL REFERENCES public.habits(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  log_date DATE NOT NULL,
  value_num INTEGER NOT NULL DEFAULT 0,
  completed_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  completed_bool BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (habit_id, log_date)
);
CREATE INDEX habit_logs_user_date_idx ON public.habit_logs(user_id, log_date);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habit_logs TO authenticated;
GRANT ALL ON public.habit_logs TO service_role;
ALTER TABLE public.habit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own logs all" ON public.habit_logs FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Seed function: creates profile + 4 starter habits on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prayer_id UUID;
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)));

  INSERT INTO public.habits (user_id, name, name_ar, type, sort_order)
  VALUES (NEW.id, 'Prayer', 'الصلاة', 'checklist', 0)
  RETURNING id INTO prayer_id;

  INSERT INTO public.habit_checklist_items (habit_id, label, sort_order) VALUES
    (prayer_id, 'Fajr', 0),
    (prayer_id, 'Dhuhr', 1),
    (prayer_id, 'Asr', 2),
    (prayer_id, 'Maghrib', 3),
    (prayer_id, 'Isha', 4);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order) VALUES
    (NEW.id, 'Quran', 'القرآن', 'counter', 'pages', 1, 1),
    (NEW.id, 'Morning Adhkar', 'أذكار الصباح', 'boolean', NULL, NULL, 2),
    (NEW.id, 'Evening Adhkar', 'أذكار المساء', 'boolean', NULL, NULL, 3);

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- FROM: 20260626052335_2505bc23-7d1a-4dc6-8269-7173f128fa89.sql
-- ============================================================
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
-- ============================================================
-- FROM: 20260626053642_98358b24-2fcc-4511-8093-0097135500df.sql
-- ============================================================

-- Add daily completion goal to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS daily_goal_pct integer NOT NULL DEFAULT 80;
ALTER TABLE public.profiles ADD CONSTRAINT daily_goal_pct_range CHECK (daily_goal_pct BETWEEN 1 AND 100);

-- Convert any existing Adhkar habits from boolean to counter with a default target
UPDATE public.habits
SET type = 'counter', unit = COALESCE(unit, 'adhkar'), target = COALESCE(target, 20)
WHERE type = 'boolean' AND (name ILIKE '%adhkar%' OR name ILIKE '%adkar%' OR name ILIKE '%dhikr%');

-- Update the new-user trigger so Adhkar habits seed as counter (percentage tracking)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  prayer_id UUID;
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)));

  INSERT INTO public.habits (user_id, name, name_ar, type, sort_order)
  VALUES (NEW.id, 'Prayer', 'الصلاة', 'checklist', 0)
  RETURNING id INTO prayer_id;

  INSERT INTO public.habit_checklist_items (habit_id, label, sort_order) VALUES
    (prayer_id, 'Fajr', 0),
    (prayer_id, 'Dhuhr', 1),
    (prayer_id, 'Asr', 2),
    (prayer_id, 'Maghrib', 3),
    (prayer_id, 'Isha', 4);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order) VALUES
    (NEW.id, 'Quran', 'القرآن', 'counter', 'pages', 1, 1),
    (NEW.id, 'Morning Adhkar', 'أذكار الصباح', 'counter', 'adhkar', 20, 2),
    (NEW.id, 'Evening Adhkar', 'أذكار المساء', 'counter', 'adhkar', 20, 3);

  RETURN NEW;
END;
$function$;

-- ============================================================
-- FROM: 20260627041410_67fc6f78-dab3-4953-aec8-a7b7c2226326.sql
-- ============================================================

CREATE TABLE public.adhkar_items (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  habit_id UUID NOT NULL REFERENCES public.habits(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  arabic TEXT NOT NULL,
  transliteration TEXT,
  translation TEXT,
  source TEXT,
  repeat_count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.adhkar_items TO authenticated;
GRANT ALL ON public.adhkar_items TO service_role;

ALTER TABLE public.adhkar_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own adhkar items all" ON public.adhkar_items
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_adhkar_items_habit ON public.adhkar_items(habit_id, sort_order);

-- Seed function for standard morning/evening adhkar for a given user/habit
CREATE OR REPLACE FUNCTION public.seed_morning_adhkar(_user_id UUID, _habit_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.adhkar_items (user_id, habit_id, sort_order, arabic, transliteration, translation, source, repeat_count) VALUES
  (_user_id, _habit_id, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...', 'Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm...', 'Ayat al-Kursi — Whoever recites this in the morning is protected from jinn until evening.', 'Al-Baqarah 2:255', 1),
  (_user_id, _habit_id, 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ', 'Qul Huwa Allāhu Aḥad...', 'Surah Al-Ikhlas — Whoever recites this three times suffices him from everything.', 'Al-Ikhlas 112', 3),
  (_user_id, _habit_id, 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ...', 'Qul aʿūdhu bi-Rabbi-l-falaq...', 'Surah Al-Falaq — Seeking refuge in the Lord of daybreak.', 'Al-Falaq 113', 3),
  (_user_id, _habit_id, 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. قُلْ أَعُوذُ بِرَبِّ النَّاسِ...', 'Qul aʿūdhu bi-Rabbi-n-nās...', 'Surah An-Nas — Seeking refuge in the Lord of mankind.', 'An-Nas 114', 3),
  (_user_id, _habit_id, 4, 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Aṣbaḥnā wa aṣbaḥa-l-mulku lillāh...', 'We have entered the morning and the dominion belongs to Allah. All praise is for Allah.', 'Muslim', 1),
  (_user_id, _habit_id, 5, 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ', 'Allāhumma bika aṣbaḥnā, wa bika amsaynā...', 'O Allah, by You we enter the morning and by You we enter the evening. By You we live and die, and to You is the resurrection.', 'Tirmidhi', 1),
  (_user_id, _habit_id, 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ...', 'Allāhumma anta Rabbī lā ilāha illā ant...', 'Sayyid al-Istighfar — The master of seeking forgiveness.', 'Bukhari', 1),
  (_user_id, _habit_id, 7, 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا', 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin nabiyyan', 'I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.', 'Abu Dawud', 3),
  (_user_id, _habit_id, 8, 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', 'Ḥasbiya-llāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿAẓīm', 'Allah is sufficient for me; there is no deity except Him. Upon Him I rely.', 'Abu Dawud', 7),
  (_user_id, _habit_id, 9, 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ', 'Bismillāhi-lladhī lā yaḍurru maʿa-smihi shay''un fī-l-arḍi wa lā fī-s-samā''i, wa Huwa-s-Samīʿu-l-ʿAlīm', 'In the name of Allah, with whose name nothing on earth or in heaven can cause harm. He is the All-Hearing, All-Knowing.', 'Abu Dawud, Tirmidhi', 3),
  (_user_id, _habit_id, 10, 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', 'SubḥānAllāhi wa biḥamdih', 'Glory and praise be to Allah.', 'Muslim', 100),
  (_user_id, _habit_id, 11, 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', 'Lā ilāha illa-llāh waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa Huwa ʿalā kulli shay''in qadīr', 'None has the right to be worshipped except Allah, alone, with no partner.', 'Bukhari, Muslim', 10),
  (_user_id, _habit_id, 12, 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ', 'Allāhumma ṣalli wa sallim ʿalā nabiyyinā Muḥammad', 'O Allah, send prayers and peace upon our Prophet Muhammad ﷺ.', 'Tabarani', 10);
END;
$$;

CREATE OR REPLACE FUNCTION public.seed_evening_adhkar(_user_id UUID, _habit_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.adhkar_items (user_id, habit_id, sort_order, arabic, transliteration, translation, source, repeat_count) VALUES
  (_user_id, _habit_id, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...', 'Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm...', 'Ayat al-Kursi — Whoever recites this in the evening is protected from jinn until morning.', 'Al-Baqarah 2:255', 1),
  (_user_id, _habit_id, 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. قُلْ هُوَ اللَّهُ أَحَدٌ...', 'Qul Huwa Allāhu Aḥad...', 'Surah Al-Ikhlas — Whoever recites this three times suffices him from everything.', 'Al-Ikhlas 112', 3),
  (_user_id, _habit_id, 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ...', 'Qul aʿūdhu bi-Rabbi-l-falaq...', 'Surah Al-Falaq.', 'Al-Falaq 113', 3),
  (_user_id, _habit_id, 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. قُلْ أَعُوذُ بِرَبِّ النَّاسِ...', 'Qul aʿūdhu bi-Rabbi-n-nās...', 'Surah An-Nas.', 'An-Nas 114', 3),
  (_user_id, _habit_id, 4, 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Amsaynā wa amsa-l-mulku lillāh...', 'We have entered the evening and the dominion belongs to Allah.', 'Muslim', 1),
  (_user_id, _habit_id, 5, 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ', 'Allāhumma bika amsaynā, wa bika aṣbaḥnā...', 'O Allah, by You we enter the evening and by You we enter the morning. To You is the final return.', 'Tirmidhi', 1),
  (_user_id, _habit_id, 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ...', 'Allāhumma anta Rabbī lā ilāha illā ant...', 'Sayyid al-Istighfar.', 'Bukhari', 1),
  (_user_id, _habit_id, 7, 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا', 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin nabiyyan', 'I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.', 'Abu Dawud', 3),
  (_user_id, _habit_id, 8, 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', 'Ḥasbiya-llāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿAẓīm', 'Allah is sufficient for me; there is no deity except Him.', 'Abu Dawud', 7),
  (_user_id, _habit_id, 9, 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ', 'Bismillāhi-lladhī lā yaḍurru...', 'In the name of Allah, with whose name nothing can cause harm.', 'Abu Dawud, Tirmidhi', 3),
  (_user_id, _habit_id, 10, 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', 'Aʿūdhu bi-kalimāti-llāhi-t-tāmmāti min sharri mā khalaq', 'I seek refuge in the perfect words of Allah from the evil of what He has created.', 'Muslim', 3),
  (_user_id, _habit_id, 11, 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', 'SubḥānAllāhi wa biḥamdih', 'Glory and praise be to Allah.', 'Muslim', 100),
  (_user_id, _habit_id, 12, 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ', 'Allāhumma ṣalli wa sallim ʿalā nabiyyinā Muḥammad', 'O Allah, send prayers and peace upon our Prophet Muhammad ﷺ.', 'Tabarani', 10);
END;
$$;

-- Updated trigger that seeds adhkar items and sets habit target to item count
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prayer_id UUID;
  morning_id UUID;
  evening_id UUID;
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)));

  INSERT INTO public.habits (user_id, name, name_ar, type, sort_order)
  VALUES (NEW.id, 'Prayer', 'الصلاة', 'checklist', 0)
  RETURNING id INTO prayer_id;

  INSERT INTO public.habit_checklist_items (habit_id, label, sort_order) VALUES
    (prayer_id, 'Fajr', 0),
    (prayer_id, 'Dhuhr', 1),
    (prayer_id, 'Asr', 2),
    (prayer_id, 'Maghrib', 3),
    (prayer_id, 'Isha', 4);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order)
  VALUES (NEW.id, 'Quran', 'القرآن', 'counter', 'pages', 1, 1);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order)
  VALUES (NEW.id, 'Morning Adhkar', 'أذكار الصباح', 'counter', 'adhkar', 13, 2)
  RETURNING id INTO morning_id;
  PERFORM public.seed_morning_adhkar(NEW.id, morning_id);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order)
  VALUES (NEW.id, 'Evening Adhkar', 'أذكار المساء', 'counter', 'adhkar', 13, 3)
  RETURNING id INTO evening_id;
  PERFORM public.seed_evening_adhkar(NEW.id, evening_id);

  RETURN NEW;
END;
$$;

-- ============================================================
-- FROM: 20260627041422_92079811-75c5-4e97-9b55-fb7336bd8aa7.sql
-- ============================================================

REVOKE EXECUTE ON FUNCTION public.seed_morning_adhkar(UUID, UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.seed_evening_adhkar(UUID, UUID) FROM PUBLIC, anon, authenticated;

-- ============================================================
-- FROM: 20260628154901_fac02c0c-d4c5-4c11-ac99-fdfeb38e7dc4.sql
-- ============================================================

-- 1. Enums
CREATE TYPE public.habit_category AS ENUM ('fard', 'sunnah');
CREATE TYPE public.habit_subcategory AS ENUM ('prayer', 'dhikr', 'quran', 'fasting', 'character');
CREATE TYPE public.recurrence_type AS ENUM ('daily', 'weekly', 'hijri_monthly', 'hijri_annual');
CREATE TYPE public.menstruation_behavior AS ENUM ('always_pause', 'never_pause', 'depends_on_madhab');

-- 2. habit_templates (global reference)
CREATE TABLE public.habit_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  name text NOT NULL,
  name_ar text,
  category public.habit_category NOT NULL,
  subcategory public.habit_subcategory NOT NULL,
  type public.habit_type NOT NULL,
  unit text,
  target integer,
  recurrence_type public.recurrence_type NOT NULL DEFAULT 'daily',
  recurrence_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  menstruation_behavior public.menstruation_behavior NOT NULL DEFAULT 'never_pause',
  description text,
  source_url text,
  sort_order integer NOT NULL DEFAULT 0,
  is_default boolean NOT NULL DEFAULT false,
  checklist_labels jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.habit_templates TO authenticated;
GRANT ALL ON public.habit_templates TO service_role;

ALTER TABLE public.habit_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "templates readable by authenticated"
  ON public.habit_templates FOR SELECT
  TO authenticated
  USING (true);

-- 3. Extend habits
ALTER TABLE public.habits
  ADD COLUMN template_id uuid REFERENCES public.habit_templates(id) ON DELETE SET NULL,
  ADD COLUMN category public.habit_category,
  ADD COLUMN subcategory public.habit_subcategory,
  ADD COLUMN recurrence_type public.recurrence_type NOT NULL DEFAULT 'daily',
  ADD COLUMN recurrence_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN menstruation_behavior public.menstruation_behavior;

-- Backfill existing seeded habits
UPDATE public.habits SET category = 'fard', subcategory = 'prayer'
  WHERE name = 'Prayer';
UPDATE public.habits SET category = 'sunnah', subcategory = 'quran', menstruation_behavior = 'depends_on_madhab'
  WHERE name = 'Quran';
UPDATE public.habits SET category = 'sunnah', subcategory = 'dhikr', menstruation_behavior = 'never_pause'
  WHERE name IN ('Morning Adhkar', 'Evening Adhkar');

-- 4. Extend profiles
ALTER TABLE public.profiles
  ADD COLUMN tracks_menstruation boolean NOT NULL DEFAULT false,
  ADD COLUMN madhab text CHECK (madhab IN ('hanafi','shafi','maliki','hanbali'));

-- 5. menstrual_cycle_logs
CREATE TABLE public.menstrual_cycle_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.menstrual_cycle_logs TO authenticated;
GRANT ALL ON public.menstrual_cycle_logs TO service_role;

ALTER TABLE public.menstrual_cycle_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own cycle logs all"
  ON public.menstrual_cycle_logs FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX menstrual_cycle_logs_user_date_idx
  ON public.menstrual_cycle_logs (user_id, start_date DESC);

-- 6. Seed habit_templates
INSERT INTO public.habit_templates
  (key, name, name_ar, category, subcategory, type, unit, target, recurrence_type, recurrence_data, menstruation_behavior, description, sort_order, is_default, checklist_labels)
VALUES
-- PRAYER (sunnah)
('sunnah_rawatib', 'Sunnah Rawatib', 'السنن الرواتب', 'sunnah', 'prayer', 'checklist', NULL, NULL, 'daily', '{}'::jsonb, 'always_pause',
 'The 12 confirmed sunnah prayers tied to the daily fard prayers.', 100, false,
 '["2 before Fajr","4 before Dhuhr","2 after Dhuhr","2 after Maghrib","2 after Isha"]'::jsonb),
('witr', 'Witr', 'الوتر', 'sunnah', 'prayer', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'always_pause',
 'Odd-numbered night prayer concluding the night.', 101, false, '[]'::jsonb),
('tahajjud', 'Tahajjud', 'التهجد', 'sunnah', 'prayer', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'always_pause',
 'Night prayer offered after sleep.', 102, false, '[]'::jsonb),
('duha', 'Duha', 'الضحى', 'sunnah', 'prayer', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'always_pause',
 'Forenoon prayer.', 103, false, '[]'::jsonb),

-- DHIKR (sunnah)
('post_prayer_tasbih', 'Post-Prayer Tasbih', 'تسبيح بعد الصلاة', 'sunnah', 'dhikr', 'counter', 'tasbih', 100, 'daily', '{}'::jsonb, 'never_pause',
 'SubhanAllah 33, Alhamdulillah 33, Allahu Akbar 34 after each fard prayer.', 200, false, '[]'::jsonb),
('istighfar', 'Istighfar', 'الاستغفار', 'sunnah', 'dhikr', 'counter', 'count', 100, 'daily', '{}'::jsonb, 'never_pause',
 'Seeking forgiveness from Allah.', 201, false, '[]'::jsonb),
('salawat', 'Salawat', 'الصلاة على النبي', 'sunnah', 'dhikr', 'counter', 'count', 100, 'daily', '{}'::jsonb, 'never_pause',
 'Sending prayers upon the Prophet ﷺ.', 202, false, '[]'::jsonb),

-- QURAN (sunnah)
('surah_kahf', 'Surah Al-Kahf', 'سورة الكهف', 'sunnah', 'quran', 'boolean', NULL, NULL, 'weekly', '{"weekdays":[5]}'::jsonb, 'depends_on_madhab',
 'Recited on Fridays — a light between the two Fridays.', 300, false, '[]'::jsonb),
('mulk_sajdah_night', 'Surah Al-Mulk & As-Sajdah (night)', 'سورة الملك والسجدة', 'sunnah', 'quran', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'depends_on_madhab',
 'Recited before sleeping each night.', 301, false, '[]'::jsonb),
('protective_surahs_sleep', 'Protective Surahs Before Sleep', 'المعوذات قبل النوم', 'sunnah', 'quran', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'depends_on_madhab',
 'Ikhlas, Falaq, Nas, and Ayat al-Kursi before sleeping.', 302, false, '[]'::jsonb),

-- FASTING (sunnah)
('mon_thu_fasting', 'Monday & Thursday Fasting', 'صيام الإثنين والخميس', 'sunnah', 'fasting', 'boolean', NULL, NULL, 'weekly', '{"weekdays":[1,4]}'::jsonb, 'always_pause',
 'Voluntary fast on Mondays and Thursdays.', 400, false, '[]'::jsonb),
('ayyam_al_bid', 'Ayyam al-Bid (White Days)', 'أيام البيض', 'sunnah', 'fasting', 'boolean', NULL, NULL, 'hijri_monthly', '{"hijri_days":[13,14,15]}'::jsonb, 'always_pause',
 'Fasting the 13th, 14th, and 15th of each Hijri month.', 401, false, '[]'::jsonb),
('six_shawwal', 'Six Days of Shawwal', 'ست من شوال', 'sunnah', 'fasting', 'boolean', NULL, NULL, 'hijri_annual', '{"hijri_month":10,"hijri_days":[1,2,3,4,5,6]}'::jsonb, 'always_pause',
 'Six voluntary fasts in the month of Shawwal.', 402, false, '[]'::jsonb),
('day_of_arafah', 'Day of Arafah', 'يوم عرفة', 'sunnah', 'fasting', 'boolean', NULL, NULL, 'hijri_annual', '{"hijri_month":12,"hijri_days":[9]}'::jsonb, 'always_pause',
 'Fasting the 9th of Dhul-Hijjah expiates the sins of two years.', 403, false, '[]'::jsonb),
('ashura', 'Ashura', 'عاشوراء', 'sunnah', 'fasting', 'boolean', NULL, NULL, 'hijri_annual', '{"hijri_month":1,"hijri_days":[9,10]}'::jsonb, 'always_pause',
 'Fasting the 9th and 10th of Muharram.', 404, false, '[]'::jsonb),
('first_nine_dhul_hijjah', 'First 9 Days of Dhul-Hijjah', 'العشر الأوائل من ذي الحجة', 'sunnah', 'fasting', 'boolean', NULL, NULL, 'hijri_annual', '{"hijri_month":12,"hijri_days":[1,2,3,4,5,6,7,8,9]}'::jsonb, 'always_pause',
 'The first nine days of Dhul-Hijjah are especially beloved to Allah.', 405, false, '[]'::jsonb),

-- CHARACTER (sunnah)
('miswak', 'Miswak', 'السواك', 'sunnah', 'character', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'never_pause',
 'Using the miswak — beloved sunnah of dental care.', 500, false, '[]'::jsonb),
('sleep_sunnah', 'Sleep Sunnah', 'سنن النوم', 'sunnah', 'character', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'never_pause',
 'Wudu before sleep, sleeping on the right side, facing the Qiblah.', 501, false, '[]'::jsonb),
('dua_home', 'Dua Entering/Leaving Home', 'دعاء دخول وخروج المنزل', 'sunnah', 'character', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'never_pause',
 'Saying the prophetic duas when entering and leaving the home.', 502, false, '[]'::jsonb),
('smile_salam', 'Smile & Give Salam First', 'التبسم وإفشاء السلام', 'sunnah', 'character', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'never_pause',
 'Smiling is charity; spreading salam strengthens love between believers.', 503, false, '[]'::jsonb),
('daily_sadaqah', 'Daily Sadaqah', 'صدقة يومية', 'sunnah', 'character', 'boolean', NULL, NULL, 'daily', '{}'::jsonb, 'never_pause',
 'Give something in charity every day, even a small amount.', 504, false, '[]'::jsonb);

-- ============================================================
-- FROM: 20260630061352_4fd9f2f9-99d1-431b-b82c-c956a643fcbb.sql
-- ============================================================

DO $$ BEGIN
  CREATE TYPE public.quran_tracking_mode AS ENUM ('pages', 'verses', 'minutes');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.habits
  ADD COLUMN IF NOT EXISTS quran_tracking_mode public.quran_tracking_mode;

UPDATE public.habits
SET quran_tracking_mode = 'pages'
WHERE quran_tracking_mode IS NULL
  AND subcategory = 'quran'
  AND type = 'counter';

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.quran_reading_state (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  habit_id UUID NOT NULL REFERENCES public.habits(id) ON DELETE CASCADE,
  surah INTEGER NOT NULL DEFAULT 1 CHECK (surah BETWEEN 1 AND 114),
  ayah INTEGER NOT NULL DEFAULT 1 CHECK (ayah >= 1),
  show_translation BOOLEAN NOT NULL DEFAULT TRUE,
  view_mode TEXT NOT NULL DEFAULT 'verse' CHECK (view_mode IN ('verse','page')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (user_id, habit_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.quran_reading_state TO authenticated;
GRANT ALL ON public.quran_reading_state TO service_role;

ALTER TABLE public.quran_reading_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own quran reading state"
  ON public.quran_reading_state
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS update_quran_reading_state_updated_at ON public.quran_reading_state;
CREATE TRIGGER update_quran_reading_state_updated_at
  BEFORE UPDATE ON public.quran_reading_state
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- FROM: 20260706120000_full_adhkar_text.sql
-- ============================================================
-- Un-truncate the morning/evening adhkar seed text (previously cut short
-- with "..." for several entries) and add numbered ayah-end marks (۝١ ۝٢ …)
-- to the short surahs so nothing requires leaving the page to look up.
--
-- Arabic for the Qur'anic portions (Ayat al-Kursi, Al-Ikhlas, Al-Falaq,
-- An-Nas) matches the Uthmani text served by api.quran.com — the same
-- source the in-app Qur'an reader uses — for consistency between the two.
-- Hadith-text duas are the standard wording from Hisn al-Muslim / Sahih
-- al-Bukhari as commonly published.

CREATE OR REPLACE FUNCTION public.seed_morning_adhkar(_user_id UUID, _habit_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.adhkar_items (user_id, habit_id, sort_order, arabic, transliteration, translation, source, repeat_count) VALUES
  (_user_id, _habit_id, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥', 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.', 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.', 'Al-Baqarah 2:255 — recite in the morning for protection until evening', 1),
  (_user_id, _habit_id, 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times', 3),
  (_user_id, _habit_id, 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times', 3),
  (_user_id, _habit_id, 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times', 3),
  (_user_id, _habit_id, 4, 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Aṣbaḥnā wa aṣbaḥa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the morning, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim', 1),
  (_user_id, _habit_id, 5, 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ', 'Allāhumma bika aṣbaḥnā, wa bika amsaynā, wa bika naḥyā, wa bika namūtu, wa ilayka-n-nushūr.', 'O Allah, by You we enter the morning and by You we enter the evening. By You we live and die, and to You is the resurrection.', 'Tirmidhi', 1),
  (_user_id, _habit_id, 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306', 1),
  (_user_id, _habit_id, 7, 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا', 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin nabiyyan', 'I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.', 'Abu Dawud — recite three times', 3),
  (_user_id, _habit_id, 8, 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', 'Ḥasbiya-llāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿAẓīm', 'Allah is sufficient for me; there is no deity except Him. Upon Him I rely, and He is Lord of the exalted throne.', 'Abu Dawud — recite seven times', 7),
  (_user_id, _habit_id, 9, 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ', 'Bismillāhi-lladhī lā yaḍurru maʿa-smihi shay''un fī-l-arḍi wa lā fī-s-samā''i, wa Huwa-s-Samīʿu-l-ʿAlīm', 'In the name of Allah, with whose name nothing on earth or in heaven can cause harm. He is the All-Hearing, All-Knowing.', 'Abu Dawud, Tirmidhi — recite three times', 3),
  (_user_id, _habit_id, 10, 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', 'SubḥānAllāhi wa biḥamdih', 'Glory and praise be to Allah.', 'Muslim — recite one hundred times', 100),
  (_user_id, _habit_id, 11, 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', 'Lā ilāha illa-llāh waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa Huwa ʿalā kulli shay''in qadīr', 'None has the right to be worshipped except Allah, alone, with no partner. To Him belongs sovereignty and praise, and He is over all things omnipotent.', 'Bukhari, Muslim — recite ten times', 10),
  (_user_id, _habit_id, 12, 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ', 'Allāhumma ṣalli wa sallim ʿalā nabiyyinā Muḥammad', 'O Allah, send prayers and peace upon our Prophet Muhammad ﷺ.', 'Tabarani — recite ten times', 10);
END;
$$;

CREATE OR REPLACE FUNCTION public.seed_evening_adhkar(_user_id UUID, _habit_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.adhkar_items (user_id, habit_id, sort_order, arabic, transliteration, translation, source, repeat_count) VALUES
  (_user_id, _habit_id, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥', 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.', 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.', 'Al-Baqarah 2:255 — recite in the evening for protection until morning', 1),
  (_user_id, _habit_id, 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times', 3),
  (_user_id, _habit_id, 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times', 3),
  (_user_id, _habit_id, 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times', 3),
  (_user_id, _habit_id, 4, 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Amsaynā wa amsa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the evening, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim', 1),
  (_user_id, _habit_id, 5, 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ', 'Allāhumma bika amsaynā, wa bika aṣbaḥnā, wa bika naḥyā, wa bika namūtu, wa ilayka-l-maṣīr.', 'O Allah, by You we enter the evening and by You we enter the morning. By You we live and die, and to You is the final return.', 'Tirmidhi', 1),
  (_user_id, _habit_id, 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306', 1),
  (_user_id, _habit_id, 7, 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا', 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin nabiyyan', 'I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.', 'Abu Dawud — recite three times', 3),
  (_user_id, _habit_id, 8, 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', 'Ḥasbiya-llāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿAẓīm', 'Allah is sufficient for me; there is no deity except Him. Upon Him I rely, and He is Lord of the exalted throne.', 'Abu Dawud — recite seven times', 7),
  (_user_id, _habit_id, 9, 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ', 'Bismillāhi-lladhī lā yaḍurru maʿa-smihi shay''un fī-l-arḍi wa lā fī-s-samā''i, wa Huwa-s-Samīʿu-l-ʿAlīm', 'In the name of Allah, with whose name nothing on earth or in heaven can cause harm. He is the All-Hearing, All-Knowing.', 'Abu Dawud, Tirmidhi — recite three times', 3),
  (_user_id, _habit_id, 10, 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', 'Aʿūdhu bi-kalimāti-llāhi-t-tāmmāti min sharri mā khalaq', 'I seek refuge in the perfect words of Allah from the evil of what He has created.', 'Muslim — recite three times', 3),
  (_user_id, _habit_id, 11, 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', 'SubḥānAllāhi wa biḥamdih', 'Glory and praise be to Allah.', 'Muslim — recite one hundred times', 100),
  (_user_id, _habit_id, 12, 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ', 'Allāhumma ṣalli wa sallim ʿalā nabiyyinā Muḥammad', 'O Allah, send prayers and peace upon our Prophet Muhammad ﷺ.', 'Tabarani — recite ten times', 10);
END;
$$;

-- Backfill adhkar_items rows that already exist in the database (the
-- functions above only run for brand-new signups) with the same full text,
-- matched by the habit's name + the item's stable sort_order.
UPDATE public.adhkar_items ai
SET arabic = v.arabic, transliteration = v.transliteration, translation = v.translation, source = v.source
FROM public.habits h,
  (VALUES
    ('Morning Adhkar'::text, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥'::text, 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.'::text, 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.'::text, 'Al-Baqarah 2:255 — recite in the morning for protection until evening'::text),
    ('Morning Adhkar', 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times'),
    ('Morning Adhkar', 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times'),
    ('Morning Adhkar', 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times'),
    ('Morning Adhkar', 4, 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Aṣbaḥnā wa aṣbaḥa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the morning, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim'),
    ('Morning Adhkar', 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306'),
    ('Evening Adhkar', 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥', 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.', 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.', 'Al-Baqarah 2:255 — recite in the evening for protection until morning'),
    ('Evening Adhkar', 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times'),
    ('Evening Adhkar', 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times'),
    ('Evening Adhkar', 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times'),
    ('Evening Adhkar', 4, 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Amsaynā wa amsa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the evening, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim'),
    ('Evening Adhkar', 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306'),
    ('Evening Adhkar', 10, 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', 'Aʿūdhu bi-kalimāti-llāhi-t-tāmmāti min sharri mā khalaq', 'I seek refuge in the perfect words of Allah from the evil of what He has created.', 'Muslim — recite three times')
  ) AS v(habit_name, sort_order, arabic, transliteration, translation, source)
WHERE h.id = ai.habit_id
  AND h.name = v.habit_name
  AND ai.sort_order = v.sort_order;

-- ============================================================
-- FROM: 20260708023607_cc5c197c-82ce-47eb-b018-74f3ff338264.sql
-- ============================================================
CREATE TABLE public.daily_duas (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  category TEXT NOT NULL,
  arabic TEXT NOT NULL,
  transliteration TEXT,
  translation TEXT,
  source TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

GRANT SELECT ON public.daily_duas TO authenticated;
GRANT ALL ON public.daily_duas TO service_role;

ALTER TABLE public.daily_duas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "daily duas readable by authenticated"
  ON public.daily_duas FOR SELECT
  TO authenticated
  USING (true);

CREATE INDEX idx_daily_duas_sort ON public.daily_duas(sort_order);

INSERT INTO public.daily_duas (category, sort_order, arabic, transliteration, translation, source) VALUES
('Waking up', 0, 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ', 'Alḥamdu lillāhi-lladhī aḥyānā baʿda mā amātanā wa ilayhi-n-nushūr.', 'All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.', 'Hisn al-Muslim #1 · Bukhari'),
('Waking up', 1, 'الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي فِي جَسَدِي وَرَدَّ عَلَيَّ رُوحِي وَأَذِنَ لِي بِذِكْرِهِ', 'Alḥamdu lillāhi-lladhī ʿāfānī fī jasadī, wa radda ʿalayya rūḥī, wa adhina lī bi-dhikrih.', 'All praise is for Allah who restored to me my health and returned my soul, and has allowed me to remember Him.', 'Hisn al-Muslim #3 · Tirmidhi'),
('Before sleeping', 2, 'بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا، بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ', 'Bismika Rabbī waḍaʿtu janbī, wa bika arfaʿuh, fa-in amsakta nafsī fa-rḥamhā, wa in arsaltahā fa-ḥfaẓhā bimā taḥfaẓu bihi ʿibādaka-ṣ-ṣāliḥīn.', 'In Your name, my Lord, I lie down, and in Your name I rise. So if You should take my soul, then have mercy upon it, and if You should return it, then protect it as You protect Your righteous servants.', 'Hisn al-Muslim #102 · Bukhari, Muslim'),
('Before sleeping', 3, 'اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا، لَكَ مَمَاتُهَا وَمَحْيَاهَا، إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا، وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ', 'Allāhumma innaka khalaqta nafsī wa anta tawaffāhā, laka mamātuhā wa maḥyāhā, in aḥyaytahā fa-ḥfaẓhā, wa in amattahā fa-ghfir lahā. Allāhumma innī as''aluka-l-ʿāfiyah.', 'O Allah, You have created my soul and You take its life; to You belongs its death and its life. If You keep it alive, then protect it, and if You take its life, then forgive it. O Allah, I ask You for good health.', 'Hisn al-Muslim #103 · Muslim'),
('Before sleeping', 4, 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا', 'Bismikallāhumma amūtu wa aḥyā.', 'In Your name, O Allah, I die and I live.', 'Hisn al-Muslim #105 · Bukhari'),
('Before sleeping', 5, 'سُبْحَانَ اللَّهِ (ثَلَاثًا وَثَلَاثِينَ) وَالْحَمْدُ لِلَّهِ (ثَلَاثًا وَثَلَاثِينَ) وَاللَّهُ أَكْبَرُ (أَرْبَعًا وَثَلَاثِينَ)', 'SubḥānAllāh (33 times), wa-l-ḥamdu lillāh (33 times), wa-llāhu akbar (34 times).', 'How perfect Allah is (33 times). All praise is for Allah (33 times). Allah is the greatest (34 times).', 'Hisn al-Muslim #106 · Bukhari, Muslim'),
('Before sleeping', 6, 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ', 'Allāhumma aslamtu nafsī ilayk, wa fawwaḍtu amrī ilayk, wa wajjahtu wajhī ilayk, wa alja''tu ẓahrī ilayk, raghbatan wa rahbatan ilayk, lā malja''a wa lā manjā minka illā ilayk, āmantu bi-kitābika-lladhī anzalt, wa bi-nabiyyika-lladhī arsalt.', 'O Allah, I submit my soul unto You, entrust my affairs unto You, turn my face towards You, and rely upon You, in hope and fear of You. There is no refuge from You except with You. I believe in Your Book which You revealed and Your Prophet whom You sent.', 'Hisn al-Muslim #111 · Bukhari, Muslim'),
('Restroom', 7, '[بِسْمِ اللَّهِ] اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ', '(Bismillāh) Allāhumma innī aʿūdhu bika mina-l-khubthi wa-l-khabā''ith.', '(In the name of Allah) O Allah, I take refuge with You from all evil and evil-doers.', 'Hisn al-Muslim #10 · Bukhari, Muslim'),
('Restroom', 8, 'غُفْرَانَكَ', 'Ghufrānak.', 'I ask You (Allah) for forgiveness.', 'Hisn al-Muslim #11 · Abu Dawud, Tirmidhi'),
('Ablution', 9, 'بِسْمِ اللَّهِ', 'Bismillāh.', 'In the name of Allah.', 'Hisn al-Muslim #12'),
('Ablution', 10, 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ', 'Ashhadu an lā ilāha illa-llāhu waḥdahu lā sharīka lah, wa ashhadu anna Muḥammadan ʿabduhu wa rasūluh.', 'I bear witness that none has the right to be worshipped except Allah, alone without partner, and I bear witness that Muhammad is His slave and Messenger.', 'Hisn al-Muslim #13 · Muslim'),
('Ablution', 11, 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ', 'Subḥānaka-llāhumma wa bi-ḥamdik, ashhadu an lā ilāha illā ant, astaghfiruka wa atūbu ilayk.', 'How perfect You are, O Allah, and I praise You. I bear witness that none has the right to be worshipped except You. I seek Your forgiveness and turn to You in repentance.', 'Hisn al-Muslim #15 · Nasa''i'),
('Leaving home', 12, 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ', 'Bismillāh, tawakkaltu ʿala-llāh, wa lā ḥawla wa lā quwwata illā billāh.', 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.', 'Hisn al-Muslim #16 · Abu Dawud, Tirmidhi'),
('Entering home', 13, 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا', 'Bismillāhi walajnā, wa bismillāhi kharajnā, wa ʿalā Rabbinā tawakkalnā.', 'In the name of Allah we enter, and in the name of Allah we leave, and upon our Lord we place our trust.', 'Hisn al-Muslim #18 · Abu Dawud'),
('Mosque', 14, 'أَعُوذُ بِاللَّهِ الْعَظِيمِ، وَبِوَجْهِهِ الْكَرِيمِ، وَسُلْطَانِهِ الْقَدِيمِ، مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ', 'Aʿūdhu billāhi-l-ʿAẓīm, wa bi-wajhihi-l-karīm, wa sulṭānihi-l-qadīm, mina-sh-shayṭāni-r-rajīm. Allāhumma-ftaḥ lī abwāba raḥmatik.', 'I take refuge with Allah, the Supreme, and with His noble Face and eternal authority, from the accursed devil. O Allah, open the gates of Your mercy for me.', 'Hisn al-Muslim #20 · Abu Dawud'),
('Mosque', 15, 'بِسْمِ اللَّهِ وَالصَّلَاةُ وَالسَّلَامُ عَلَى رَسُولِ اللَّهِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ، اللَّهُمَّ اعْصِمْنِي مِنَ الشَّيْطَانِ الرَّجِيمِ', 'Bismillāh, wa-ṣ-ṣalātu wa-s-salāmu ʿalā rasūlillāh. Allāhumma innī as''aluka min faḍlik. Allāhumma-ʿṣimnī mina-sh-shayṭāni-r-rajīm.', 'In the name of Allah, and prayers and peace be upon the Messenger of Allah. O Allah, I ask You from Your favor. O Allah, guard me from the accursed devil.', 'Hisn al-Muslim #21 · Ibn Majah'),
('Call to prayer', 16, 'وَأَنَا أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، رَضِيتُ بِاللَّهِ رَبًّا، وَبِمُحَمَّدٍ رَسُولًا، وَبِالْإِسْلَامِ دِينًا', 'Wa ana ashhadu an lā ilāha illa-llāhu waḥdahu lā sharīka lah, wa anna Muḥammadan ʿabduhu wa rasūluh, raḍītu billāhi Rabban, wa bi-Muḥammadin rasūlan, wa bil-Islāmi dīnā.', 'And I too bear witness that none has the right to be worshipped except Allah, alone, without partner, and that Muhammad is His slave and Messenger. I am pleased with Allah as Lord, Muhammad as Messenger, and Islam as religion.', 'Hisn al-Muslim #23 · Muslim'),
('Call to prayer', 17, 'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ، وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ، وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ', 'Allāhumma Rabba hādhihi-d-daʿwati-t-tāmmah, wa-ṣ-ṣalāti-l-qā''imah, āti Muḥammadani-l-wasīlata wa-l-faḍīlah, wa-bʿathhu maqāman maḥmūdani-lladhī waʿadtah.', 'O Allah, Lord of this perfect call and of the prayer about to be established, grant Muhammad the intercession and favor, and raise him to the praised station You have promised him.', 'Hisn al-Muslim #25 · Bukhari'),
('Dressing', 18, 'الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ', 'Alḥamdu lillāhi-lladhī kasānī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah.', 'All praise is for Allah who has clothed me with this garment and provided it for me, with no power nor might from myself.', 'Hisn al-Muslim #5 · Abu Dawud, Tirmidhi'),
('Beginning of prayer', 19, 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ', 'Subḥānaka-llāhumma wa bi-ḥamdik, wa tabāraka-smuk, wa taʿālā jadduk, wa lā ilāha ghayruk.', 'How perfect You are, O Allah, and I praise You. Blessed is Your name, and exalted is Your majesty, and none has the right to be worshipped except You.', 'Hisn al-Muslim #28 · Abu Dawud, Tirmidhi'),
('Beginning of prayer', 20, 'اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللَّهُمَّ نَقِّنِي مِنْ خَطَايَايَ كَمَا يُنَقَّى الثَّوْبُ الْأَبْيَضُ مِنَ الدَّنَسِ، اللَّهُمَّ اغْسِلْنِي مِنْ خَطَايَايَ بِالثَّلْجِ وَالْمَاءِ وَالْبَرَدِ', 'Allāhumma bāʿid baynī wa bayna khaṭāyāya kamā bāʿadta bayna-l-mashriqi wa-l-maghrib. Allāhumma naqqinī min khaṭāyāya kamā yunaqqa-th-thawbu-l-abyaḍu mina-d-danas. Allāhumma-ghsilnī min khaṭāyāya bi-th-thalji wa-l-mā''i wa-l-barad.', 'O Allah, distance me from my sins as You have distanced the East from the West. O Allah, purify me of my sins as a white garment is purified of filth. O Allah, cleanse me of my sins with snow, water, and hail.', 'Hisn al-Muslim #27 · Bukhari, Muslim');
-- ============================================================
-- FROM: 20260708130000_prayer_menstruation_pause.sql
-- ============================================================
-- Prayer buttons are getting an on-time/late/missed/paused state (built in
-- the app layer via the existing habit_logs.completed_items jsonb and
-- value_num columns — no new columns needed here). The "paused" state is
-- only ever reachable for habits where menstruation_behavior = 'always_pause',
-- which is correct fiqh for the five daily prayers, Sunnah Rawatib, Witr,
-- Tahajjud, and Duha across all four madhabs (menstruating women neither
-- pray nor make up missed prayers).
--
-- habit_templates already has 'always_pause' seeded correctly for
-- sunnah_rawatib / witr / tahajjud / duha (see the 20260628154901
-- migration). The one gap is the original "Prayer" (fard) habit, which is
-- created directly by the handle_new_user() trigger rather than from a
-- template, and never had menstruation_behavior set.

-- 1. Backfill existing users' rows.
UPDATE public.habits
SET menstruation_behavior = 'always_pause'
WHERE subcategory = 'prayer' AND menstruation_behavior IS NULL;

-- Prayer itself predates the category/subcategory backfill in some very
-- early accounts too — catch it by name as a belt-and-suspenders fallback.
UPDATE public.habits
SET category = 'fard', subcategory = 'prayer', menstruation_behavior = 'always_pause'
WHERE name = 'Prayer' AND menstruation_behavior IS NULL;

-- 2. Fix the signup trigger so future accounts get this set from the start.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prayer_id UUID;
  morning_id UUID;
  evening_id UUID;
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)));

  INSERT INTO public.habits
    (user_id, name, name_ar, type, sort_order, category, subcategory, menstruation_behavior)
  VALUES
    (NEW.id, 'Prayer', 'الصلاة', 'checklist', 0, 'fard', 'prayer', 'always_pause')
  RETURNING id INTO prayer_id;

  INSERT INTO public.habit_checklist_items (habit_id, label, sort_order) VALUES
    (prayer_id, 'Fajr', 0),
    (prayer_id, 'Dhuhr', 1),
    (prayer_id, 'Asr', 2),
    (prayer_id, 'Maghrib', 3),
    (prayer_id, 'Isha', 4);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order)
  VALUES (NEW.id, 'Quran', 'القرآن', 'counter', 'pages', 1, 1);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order)
  VALUES (NEW.id, 'Morning Adhkar', 'أذكار الصباح', 'counter', 'adhkar', 13, 2)
  RETURNING id INTO morning_id;
  PERFORM public.seed_morning_adhkar(NEW.id, morning_id);

  INSERT INTO public.habits (user_id, name, name_ar, type, unit, target, sort_order)
  VALUES (NEW.id, 'Evening Adhkar', 'أذكار المساء', 'counter', 'adhkar', 13, 3)
  RETURNING id INTO evening_id;
  PERFORM public.seed_evening_adhkar(NEW.id, evening_id);

  RETURN NEW;
END;
$$;

COMMIT;
