-- Un-truncate the morning/evening adhkar seed text (previously cut short
-- with "..." for several entries) and add numbered ayah-end marks (۝١ ۝٢ …)
-- to the short surahs so nothing requires leaving the page to look up.
--
-- Arabic for the Qur'anic portions (Ayat al-Kursi, Al-Ikhlas, Al-Falaq,
-- An-Nas) matches the Uthmani text served by api.quran.com — the same
-- source the in-app Qur'an reader uses — for consistency between the two.
-- Hadith-text duas are the standard wording from Hisn al-Muslim / Sahih
-- al-Bukhari as commonly published.

CREATE OR REPLACE FUNCTION public.seed_morning_adhkar(_user_id UUID, _habit_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.adhkar_items (user_id, habit_id, sort_order, arabic, transliteration, translation, source, repeat_count) VALUES
  (_user_id, _habit_id, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥', 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.', 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.', 'Al-Baqarah 2:255 — recite in the morning for protection until evening', 1),
  (_user_id, _habit_id, 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times', 3),
  (_user_id, _habit_id, 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times', 3),
  (_user_id, _habit_id, 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times', 3),
  (_user_id, _habit_id, 4, 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Aṣbaḥnā wa aṣbaḥa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the morning, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim', 1),
  (_user_id, _habit_id, 5, 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ', 'Allāhumma bika aṣbaḥnā, wa bika amsaynā, wa bika naḥyā, wa bika namūtu, wa ilayka-n-nushūr.', 'O Allah, by You we enter the morning and by You we enter the evening. By You we live and die, and to You is the resurrection.', 'Tirmidhi', 1),
  (_user_id, _habit_id, 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306', 1),
  (_user_id, _habit_id, 7, 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا', 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin nabiyyan', 'I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.', 'Abu Dawud — recite three times', 3),
  (_user_id, _habit_id, 8, 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', 'Ḥasbiya-llāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿAẓīm', 'Allah is sufficient for me; there is no deity except Him. Upon Him I rely, and He is Lord of the exalted throne.', 'Abu Dawud — recite seven times', 7),
  (_user_id, _habit_id, 9, 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ', 'Bismillāhi-lladhī lā yaḍurru maʿa-smihi shay''un fī-l-arḍi wa lā fī-s-samā''i, wa Huwa-s-Samīʿu-l-ʿAlīm', 'In the name of Allah, with whose name nothing on earth or in heaven can cause harm. He is the All-Hearing, All-Knowing.', 'Abu Dawud, Tirmidhi — recite three times', 3),
  (_user_id, _habit_id, 10, 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', 'SubḥānAllāhi wa biḥamdih', 'Glory and praise be to Allah.', 'Muslim — recite one hundred times', 100),
  (_user_id, _habit_id, 11, 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', 'Lā ilāha illa-llāh waḥdahu lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa Huwa ʿalā kulli shay''in qadīr', 'None has the right to be worshipped except Allah, alone, with no partner. To Him belongs sovereignty and praise, and He is over all things omnipotent.', 'Bukhari, Muslim — recite ten times', 10),
  (_user_id, _habit_id, 12, 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ', 'Allāhumma ṣalli wa sallim ʿalā nabiyyinā Muḥammad', 'O Allah, send prayers and peace upon our Prophet Muhammad ﷺ.', 'Tabarani — recite ten times', 10);
END;
$$;

CREATE OR REPLACE FUNCTION public.seed_evening_adhkar(_user_id UUID, _habit_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.adhkar_items (user_id, habit_id, sort_order, arabic, transliteration, translation, source, repeat_count) VALUES
  (_user_id, _habit_id, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥', 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.', 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.', 'Al-Baqarah 2:255 — recite in the evening for protection until morning', 1),
  (_user_id, _habit_id, 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times', 3),
  (_user_id, _habit_id, 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times', 3),
  (_user_id, _habit_id, 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times', 3),
  (_user_id, _habit_id, 4, 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Amsaynā wa amsa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the evening, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim', 1),
  (_user_id, _habit_id, 5, 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ', 'Allāhumma bika amsaynā, wa bika aṣbaḥnā, wa bika naḥyā, wa bika namūtu, wa ilayka-l-maṣīr.', 'O Allah, by You we enter the evening and by You we enter the morning. By You we live and die, and to You is the final return.', 'Tirmidhi', 1),
  (_user_id, _habit_id, 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306', 1),
  (_user_id, _habit_id, 7, 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا', 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin nabiyyan', 'I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.', 'Abu Dawud — recite three times', 3),
  (_user_id, _habit_id, 8, 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', 'Ḥasbiya-llāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿAẓīm', 'Allah is sufficient for me; there is no deity except Him. Upon Him I rely, and He is Lord of the exalted throne.', 'Abu Dawud — recite seven times', 7),
  (_user_id, _habit_id, 9, 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ', 'Bismillāhi-lladhī lā yaḍurru maʿa-smihi shay''un fī-l-arḍi wa lā fī-s-samā''i, wa Huwa-s-Samīʿu-l-ʿAlīm', 'In the name of Allah, with whose name nothing on earth or in heaven can cause harm. He is the All-Hearing, All-Knowing.', 'Abu Dawud, Tirmidhi — recite three times', 3),
  (_user_id, _habit_id, 10, 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', 'Aʿūdhu bi-kalimāti-llāhi-t-tāmmāti min sharri mā khalaq', 'I seek refuge in the perfect words of Allah from the evil of what He has created.', 'Muslim — recite three times', 3),
  (_user_id, _habit_id, 11, 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ', 'SubḥānAllāhi wa biḥamdih', 'Glory and praise be to Allah.', 'Muslim — recite one hundred times', 100),
  (_user_id, _habit_id, 12, 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ', 'Allāhumma ṣalli wa sallim ʿalā nabiyyinā Muḥammad', 'O Allah, send prayers and peace upon our Prophet Muhammad ﷺ.', 'Tabarani — recite ten times', 10);
END;
$$;

-- Backfill adhkar_items rows that already exist in the database (the
-- functions above only run for brand-new signups) with the same full text,
-- matched by the habit's name + the item's stable sort_order.
UPDATE public.adhkar_items ai
SET arabic = v.arabic, transliteration = v.transliteration, translation = v.translation, source = v.source
FROM public.habits h,
  (VALUES
    ('Morning Adhkar'::text, 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥'::text, 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.'::text, 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.'::text, 'Al-Baqarah 2:255 — recite in the morning for protection until evening'::text),
    ('Morning Adhkar', 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times'),
    ('Morning Adhkar', 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times'),
    ('Morning Adhkar', 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times'),
    ('Morning Adhkar', 4, 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Aṣbaḥnā wa aṣbaḥa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the morning, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim'),
    ('Morning Adhkar', 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306'),
    ('Evening Adhkar', 0, 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَّهُ مَا فِى السَّمَاوَاتِ وَمَا فِى الْأَرْضِ مَن ذَا الَّذِى يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَآءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِىُّ الْعَظِيمُ ۝٢٥٥', 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa, al-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatun wa lā nawm, lahū mā fī-s-samāwāti wa mā fī-l-arḍ, man dhā-lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''in min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā, wa Huwa-l-ʿAliyyu-l-ʿAẓīm.', 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.', 'Al-Baqarah 2:255 — recite in the evening for protection until morning'),
    ('Evening Adhkar', 1, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ۝١ اللَّهُ الصَّمَدُ ۝٢ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝٣ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ۝٤', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul Huwa Allāhu Aḥad. Allāhu-ṣ-Ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, who is One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 'Al-Ikhlas 112 — recite three times'),
    ('Evening Adhkar', 2, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝١ مِنْ شَرِّ مَا خَلَقَ ۝٢ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝٣ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝٤ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ ۝٥', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-l-falaq. Min sharri mā khalaq. Wa min sharri ghāsiqin idhā waqab. Wa min sharri-n-naffāthāti fi-l-ʿuqad. Wa min sharri ḥāsidin idhā ḥasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 'Al-Falaq 113 — recite three times'),
    ('Evening Adhkar', 3, 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝١ مَلِكِ النَّاسِ ۝٢ إِلَهِ النَّاسِ ۝٣ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝٤ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝٥ مِنَ الْجِنَّةِ وَالنَّاسِ ۝٦', 'Bismillāhi-r-Raḥmāni-r-Raḥīm. Qul aʿūdhu bi-Rabbi-n-nās. Maliki-n-nās. Ilāhi-n-nās. Min sharri-l-waswāsi-l-khannās. Alladhī yuwaswisu fī ṣudūri-n-nās. Mina-l-jinnati wa-n-nās.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer - who whispers into the breasts of mankind - from among the jinn and mankind."', 'An-Nas 114 — recite three times'),
    ('Evening Adhkar', 4, 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ', 'Amsaynā wa amsa-l-mulku lillāh, wa-l-ḥamdu lillāh, lā ilāha illa-llāhu waḥdahu lā sharīka lah.', 'We have entered the evening, and with it all sovereignty belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.', 'Muslim'),
    ('Evening Adhkar', 6, 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ', 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika ma-staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi-niʿmatika ʿalayya, wa abū''u bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru-dh-dhunūba illā ant.', 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.', 'Sayyid al-Istighfar — Bukhari 6306'),
    ('Evening Adhkar', 10, 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', 'Aʿūdhu bi-kalimāti-llāhi-t-tāmmāti min sharri mā khalaq', 'I seek refuge in the perfect words of Allah from the evil of what He has created.', 'Muslim — recite three times')
  ) AS v(habit_name, sort_order, arabic, transliteration, translation, source)
WHERE h.id = ai.habit_id
  AND h.name = v.habit_name
  AND ai.sort_order = v.sort_order;
